name: CI

on: pull_request

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Build stepik_export image
        if: ${{ !cancelled() }}
        run: |
          ./build.sh stepik_export
      - name: Build moodle_export image
        if: ${{ !cancelled() }}
        run: |
          ./build.sh moodle_export
      - name: Build checker_export image
        if: ${{ !cancelled() }}
        run: |
          ./build.sh checker_export
